### PR TITLE
Added CSS for interactivity warning option

### PR DESCRIPTION
**Pull request by jlstevens**
Fairly ugly right now and will be improved. Right now the goal is to show what is necessary for the interactivity warning PR (https://github.com/pyviz-dev/nbsite/pull/191) on nbsite.

### CODE REVIEW

**Comment by jlstevens** [comment]
Here are some screenshot of what it looks like against the current version of https://github.com/pyviz-dev/nbsite/pull/191:

Full width:

</img>

Squashed to approx. half the screen:

</img>

I think it is serviceable now but happy to take any suggestions @jbednar @philippjfr !

**Comment by jbednar** [comment]
Looks good. Maybe make the font size a little smaller so that it doesn't stretch out so much when squashed? Will the warning stay on the screen the whole time, after a user scrolls down?

**Comment by jlstevens** [comment]
> Will the warning stay on the screen the whole time, after a user scrolls down?

Yes. Here is an example:

</img>

> Maybe make the font size a little smaller so that it doesn't stretch out so much when squashed

Sure though as a warning it should still be easy to read. Right now the CSS isn't specifying anything about the font size so I'll have to find what the default is and then pick something smaller.

**Comment by jbednar** [comment]
Ok, if it's always there, sounds perfect!

Can't you just set it to `smaller`?

**Comment by jlstevens** [comment]
Here it is using `smaller`:

image

**Comment by jbednar** [comment]
Looks good to me!

**Comment by jlstevens** [comment]
I'll go ahead and merge and test with an nbsite dev release.

**Comment by philippjfr** [comment]
Why was this added to the theme and not the nbsite.css?

**Comment by jlstevens** [comment]
It could have gone either way...the interactivity warning seemed to be more of a holoviz preference than an nbsite preference but seeing as the option to enable/disable it is at the nbsite level, that point is rather moot. If you wish to move this CSS to nbsite.css (and it works!) then that is fine with me.

**Comment by philippjfr** [comment]
Not totally straightforward as you say, it does need adjusting depending on the theme. But it is very surprising for the warning to show up at the bottom of the page instead of floating when using another theme.

**Comment by jlstevens** [comment]
I suppose I didn't consider this option being used with other themes (or at least other themes without this bit of CSS added). I'm happy for this CSS to be moved to nbsite.css instead.

**Comment by jlstevens** [comment]
I guess the nicest thing would be globally sensible options in `nbsite.css` (such as the floating option you mention) and any other necessary tweaks added at the theme level.

**Pull request merged**
